name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Cambia a la rama que estés usando, si no es 'main'

jobs:
  sonarcloud:
    runs-on: windows-latest  # Puedes cambiar a otra versión de Windows si es necesario
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1

      - name: Run SonarScanner
        run: |
          dotnet-sonarscanner begin /k:"Pruebas-Sonarqube_prueba-ex" /o:"pruebas-sonarqube" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build GUARDERIA.sln
          dotnet-sonarscanner end
