name: PMD Analysis

on:
  push:
    branches:
      - main

jobs:
  pmd-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download PMD from GitHub repository
        run: |
          # Descarga el archivo ZIP de PMD desde el repositorio
          wget https://github.com/yourusername/yourrepo/raw/main/assets/pmd/pmd-bin-7.12.0.zip -O pmd.zip
          unzip pmd.zip -d pmd

      - name: Run PMD analysis
        run: |
          cd pmd
          ./bin/pmd -d ../ -R rulesets/java/quickstart.xml -f text
