name: PMD Setup and Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Descomprimir archivo PMD
        run: |
          mkdir -p ~/pmd
          cp .github/assets/pmd/pmd-dist-7.12.0-bin.zip ~/pmd/
          cd ~/pmd
          unzip pmd-dist-7.12.0-bin.zip

      - name: Verificar instalaci칩n de PMD
        run: |
          cd ~/pmd/pmd-bin-7.12.0/bin
          ./pmd --version

      - name: Ejecutar an치lisis de c칩digo con PMD
        run: |
          cd ~/pmd/pmd-bin-7.12.0/bin
          ./pmd -d ~/Desktop/GUARDERIA/src -R ~/pmd/pmd-bin-7.12.0/rulesets/java/quickstart.xml -f text
          
      - name: Subir resultados del an치lisis
        uses: actions/upload-artifact@v4
        with:
          name: pmd-results
          path: ~/pmd/pmd-bin-7.12.0/bin
