name: PMD Static Analysis

on:
  push:
    branches:
      - '*'  # Esto hará que el flujo de trabajo se ejecute en cualquier rama

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Asegúrate de usar una versión compatible con PMD

      - name: Install PMD
        run: |
          mkdir -p ~/pmd
          unzip pmd-dist-7.12.0-bin.zip -d ~/pmd
          echo "$HOME/pmd/pmd-bin-7.12.0/bin" >> $GITHUB_PATH

      - name: Run PMD
        run: |
          ~/pmd/pmd-bin-7.12.0/bin/run.sh pmd -d ./src -R rulesets/java/quickstart.xml -f text
